
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SpinLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SpinLog
 * 
 */
export type SpinLogModel = runtime.Types.Result.DefaultSelection<Prisma.$SpinLogPayload>

export type AggregateSpinLog = {
  _count: SpinLogCountAggregateOutputType | null
  _avg: SpinLogAvgAggregateOutputType | null
  _sum: SpinLogSumAggregateOutputType | null
  _min: SpinLogMinAggregateOutputType | null
  _max: SpinLogMaxAggregateOutputType | null
}

export type SpinLogAvgAggregateOutputType = {
  id: number | null
  employeeId: number | null
  prizeId: number | null
}

export type SpinLogSumAggregateOutputType = {
  id: number | null
  employeeId: number | null
  prizeId: number | null
}

export type SpinLogMinAggregateOutputType = {
  id: number | null
  employeeId: number | null
  prizeId: number | null
  timestamp: Date | null
}

export type SpinLogMaxAggregateOutputType = {
  id: number | null
  employeeId: number | null
  prizeId: number | null
  timestamp: Date | null
}

export type SpinLogCountAggregateOutputType = {
  id: number
  employeeId: number
  prizeId: number
  timestamp: number
  _all: number
}


export type SpinLogAvgAggregateInputType = {
  id?: true
  employeeId?: true
  prizeId?: true
}

export type SpinLogSumAggregateInputType = {
  id?: true
  employeeId?: true
  prizeId?: true
}

export type SpinLogMinAggregateInputType = {
  id?: true
  employeeId?: true
  prizeId?: true
  timestamp?: true
}

export type SpinLogMaxAggregateInputType = {
  id?: true
  employeeId?: true
  prizeId?: true
  timestamp?: true
}

export type SpinLogCountAggregateInputType = {
  id?: true
  employeeId?: true
  prizeId?: true
  timestamp?: true
  _all?: true
}

export type SpinLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SpinLog to aggregate.
   */
  where?: Prisma.SpinLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpinLogs to fetch.
   */
  orderBy?: Prisma.SpinLogOrderByWithRelationInput | Prisma.SpinLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SpinLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpinLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpinLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SpinLogs
  **/
  _count?: true | SpinLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SpinLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SpinLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SpinLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SpinLogMaxAggregateInputType
}

export type GetSpinLogAggregateType<T extends SpinLogAggregateArgs> = {
      [P in keyof T & keyof AggregateSpinLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSpinLog[P]>
    : Prisma.GetScalarType<T[P], AggregateSpinLog[P]>
}




export type SpinLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SpinLogWhereInput
  orderBy?: Prisma.SpinLogOrderByWithAggregationInput | Prisma.SpinLogOrderByWithAggregationInput[]
  by: Prisma.SpinLogScalarFieldEnum[] | Prisma.SpinLogScalarFieldEnum
  having?: Prisma.SpinLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SpinLogCountAggregateInputType | true
  _avg?: SpinLogAvgAggregateInputType
  _sum?: SpinLogSumAggregateInputType
  _min?: SpinLogMinAggregateInputType
  _max?: SpinLogMaxAggregateInputType
}

export type SpinLogGroupByOutputType = {
  id: number
  employeeId: number
  prizeId: number | null
  timestamp: Date
  _count: SpinLogCountAggregateOutputType | null
  _avg: SpinLogAvgAggregateOutputType | null
  _sum: SpinLogSumAggregateOutputType | null
  _min: SpinLogMinAggregateOutputType | null
  _max: SpinLogMaxAggregateOutputType | null
}

type GetSpinLogGroupByPayload<T extends SpinLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SpinLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SpinLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SpinLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SpinLogGroupByOutputType[P]>
      }
    >
  >



export type SpinLogWhereInput = {
  AND?: Prisma.SpinLogWhereInput | Prisma.SpinLogWhereInput[]
  OR?: Prisma.SpinLogWhereInput[]
  NOT?: Prisma.SpinLogWhereInput | Prisma.SpinLogWhereInput[]
  id?: Prisma.IntFilter<"SpinLog"> | number
  employeeId?: Prisma.IntFilter<"SpinLog"> | number
  prizeId?: Prisma.IntNullableFilter<"SpinLog"> | number | null
  timestamp?: Prisma.DateTimeFilter<"SpinLog"> | Date | string
}

export type SpinLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  employeeId?: Prisma.SortOrder
  prizeId?: Prisma.SortOrderInput | Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type SpinLogWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SpinLogWhereInput | Prisma.SpinLogWhereInput[]
  OR?: Prisma.SpinLogWhereInput[]
  NOT?: Prisma.SpinLogWhereInput | Prisma.SpinLogWhereInput[]
  employeeId?: Prisma.IntFilter<"SpinLog"> | number
  prizeId?: Prisma.IntNullableFilter<"SpinLog"> | number | null
  timestamp?: Prisma.DateTimeFilter<"SpinLog"> | Date | string
}, "id">

export type SpinLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  employeeId?: Prisma.SortOrder
  prizeId?: Prisma.SortOrderInput | Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  _count?: Prisma.SpinLogCountOrderByAggregateInput
  _avg?: Prisma.SpinLogAvgOrderByAggregateInput
  _max?: Prisma.SpinLogMaxOrderByAggregateInput
  _min?: Prisma.SpinLogMinOrderByAggregateInput
  _sum?: Prisma.SpinLogSumOrderByAggregateInput
}

export type SpinLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.SpinLogScalarWhereWithAggregatesInput | Prisma.SpinLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.SpinLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SpinLogScalarWhereWithAggregatesInput | Prisma.SpinLogScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"SpinLog"> | number
  employeeId?: Prisma.IntWithAggregatesFilter<"SpinLog"> | number
  prizeId?: Prisma.IntNullableWithAggregatesFilter<"SpinLog"> | number | null
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"SpinLog"> | Date | string
}

export type SpinLogCreateInput = {
  employeeId: number
  prizeId?: number | null
  timestamp?: Date | string
}

export type SpinLogUncheckedCreateInput = {
  id?: number
  employeeId: number
  prizeId?: number | null
  timestamp?: Date | string
}

export type SpinLogUpdateInput = {
  employeeId?: Prisma.IntFieldUpdateOperationsInput | number
  prizeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SpinLogUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  employeeId?: Prisma.IntFieldUpdateOperationsInput | number
  prizeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SpinLogCreateManyInput = {
  id?: number
  employeeId: number
  prizeId?: number | null
  timestamp?: Date | string
}

export type SpinLogUpdateManyMutationInput = {
  employeeId?: Prisma.IntFieldUpdateOperationsInput | number
  prizeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SpinLogUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  employeeId?: Prisma.IntFieldUpdateOperationsInput | number
  prizeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SpinLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  employeeId?: Prisma.SortOrder
  prizeId?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type SpinLogAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  employeeId?: Prisma.SortOrder
  prizeId?: Prisma.SortOrder
}

export type SpinLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  employeeId?: Prisma.SortOrder
  prizeId?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type SpinLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  employeeId?: Prisma.SortOrder
  prizeId?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type SpinLogSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  employeeId?: Prisma.SortOrder
  prizeId?: Prisma.SortOrder
}



export type SpinLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  employeeId?: boolean
  prizeId?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["spinLog"]>

export type SpinLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  employeeId?: boolean
  prizeId?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["spinLog"]>

export type SpinLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  employeeId?: boolean
  prizeId?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["spinLog"]>

export type SpinLogSelectScalar = {
  id?: boolean
  employeeId?: boolean
  prizeId?: boolean
  timestamp?: boolean
}

export type SpinLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "employeeId" | "prizeId" | "timestamp", ExtArgs["result"]["spinLog"]>

export type $SpinLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SpinLog"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    employeeId: number
    prizeId: number | null
    timestamp: Date
  }, ExtArgs["result"]["spinLog"]>
  composites: {}
}

export type SpinLogGetPayload<S extends boolean | null | undefined | SpinLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SpinLogPayload, S>

export type SpinLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SpinLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SpinLogCountAggregateInputType | true
  }

export interface SpinLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SpinLog'], meta: { name: 'SpinLog' } }
  /**
   * Find zero or one SpinLog that matches the filter.
   * @param {SpinLogFindUniqueArgs} args - Arguments to find a SpinLog
   * @example
   * // Get one SpinLog
   * const spinLog = await prisma.spinLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SpinLogFindUniqueArgs>(args: Prisma.SelectSubset<T, SpinLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SpinLogClient<runtime.Types.Result.GetResult<Prisma.$SpinLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SpinLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SpinLogFindUniqueOrThrowArgs} args - Arguments to find a SpinLog
   * @example
   * // Get one SpinLog
   * const spinLog = await prisma.spinLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SpinLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SpinLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SpinLogClient<runtime.Types.Result.GetResult<Prisma.$SpinLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SpinLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpinLogFindFirstArgs} args - Arguments to find a SpinLog
   * @example
   * // Get one SpinLog
   * const spinLog = await prisma.spinLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SpinLogFindFirstArgs>(args?: Prisma.SelectSubset<T, SpinLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__SpinLogClient<runtime.Types.Result.GetResult<Prisma.$SpinLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SpinLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpinLogFindFirstOrThrowArgs} args - Arguments to find a SpinLog
   * @example
   * // Get one SpinLog
   * const spinLog = await prisma.spinLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SpinLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SpinLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SpinLogClient<runtime.Types.Result.GetResult<Prisma.$SpinLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SpinLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpinLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SpinLogs
   * const spinLogs = await prisma.spinLog.findMany()
   * 
   * // Get first 10 SpinLogs
   * const spinLogs = await prisma.spinLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const spinLogWithIdOnly = await prisma.spinLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SpinLogFindManyArgs>(args?: Prisma.SelectSubset<T, SpinLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpinLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SpinLog.
   * @param {SpinLogCreateArgs} args - Arguments to create a SpinLog.
   * @example
   * // Create one SpinLog
   * const SpinLog = await prisma.spinLog.create({
   *   data: {
   *     // ... data to create a SpinLog
   *   }
   * })
   * 
   */
  create<T extends SpinLogCreateArgs>(args: Prisma.SelectSubset<T, SpinLogCreateArgs<ExtArgs>>): Prisma.Prisma__SpinLogClient<runtime.Types.Result.GetResult<Prisma.$SpinLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SpinLogs.
   * @param {SpinLogCreateManyArgs} args - Arguments to create many SpinLogs.
   * @example
   * // Create many SpinLogs
   * const spinLog = await prisma.spinLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SpinLogCreateManyArgs>(args?: Prisma.SelectSubset<T, SpinLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SpinLogs and returns the data saved in the database.
   * @param {SpinLogCreateManyAndReturnArgs} args - Arguments to create many SpinLogs.
   * @example
   * // Create many SpinLogs
   * const spinLog = await prisma.spinLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SpinLogs and only return the `id`
   * const spinLogWithIdOnly = await prisma.spinLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SpinLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SpinLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpinLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SpinLog.
   * @param {SpinLogDeleteArgs} args - Arguments to delete one SpinLog.
   * @example
   * // Delete one SpinLog
   * const SpinLog = await prisma.spinLog.delete({
   *   where: {
   *     // ... filter to delete one SpinLog
   *   }
   * })
   * 
   */
  delete<T extends SpinLogDeleteArgs>(args: Prisma.SelectSubset<T, SpinLogDeleteArgs<ExtArgs>>): Prisma.Prisma__SpinLogClient<runtime.Types.Result.GetResult<Prisma.$SpinLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SpinLog.
   * @param {SpinLogUpdateArgs} args - Arguments to update one SpinLog.
   * @example
   * // Update one SpinLog
   * const spinLog = await prisma.spinLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SpinLogUpdateArgs>(args: Prisma.SelectSubset<T, SpinLogUpdateArgs<ExtArgs>>): Prisma.Prisma__SpinLogClient<runtime.Types.Result.GetResult<Prisma.$SpinLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SpinLogs.
   * @param {SpinLogDeleteManyArgs} args - Arguments to filter SpinLogs to delete.
   * @example
   * // Delete a few SpinLogs
   * const { count } = await prisma.spinLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SpinLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, SpinLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SpinLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpinLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SpinLogs
   * const spinLog = await prisma.spinLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SpinLogUpdateManyArgs>(args: Prisma.SelectSubset<T, SpinLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SpinLogs and returns the data updated in the database.
   * @param {SpinLogUpdateManyAndReturnArgs} args - Arguments to update many SpinLogs.
   * @example
   * // Update many SpinLogs
   * const spinLog = await prisma.spinLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SpinLogs and only return the `id`
   * const spinLogWithIdOnly = await prisma.spinLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SpinLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SpinLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpinLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SpinLog.
   * @param {SpinLogUpsertArgs} args - Arguments to update or create a SpinLog.
   * @example
   * // Update or create a SpinLog
   * const spinLog = await prisma.spinLog.upsert({
   *   create: {
   *     // ... data to create a SpinLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SpinLog we want to update
   *   }
   * })
   */
  upsert<T extends SpinLogUpsertArgs>(args: Prisma.SelectSubset<T, SpinLogUpsertArgs<ExtArgs>>): Prisma.Prisma__SpinLogClient<runtime.Types.Result.GetResult<Prisma.$SpinLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SpinLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpinLogCountArgs} args - Arguments to filter SpinLogs to count.
   * @example
   * // Count the number of SpinLogs
   * const count = await prisma.spinLog.count({
   *   where: {
   *     // ... the filter for the SpinLogs we want to count
   *   }
   * })
  **/
  count<T extends SpinLogCountArgs>(
    args?: Prisma.Subset<T, SpinLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SpinLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SpinLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpinLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SpinLogAggregateArgs>(args: Prisma.Subset<T, SpinLogAggregateArgs>): Prisma.PrismaPromise<GetSpinLogAggregateType<T>>

  /**
   * Group by SpinLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpinLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SpinLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SpinLogGroupByArgs['orderBy'] }
      : { orderBy?: SpinLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SpinLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSpinLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SpinLog model
 */
readonly fields: SpinLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SpinLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SpinLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SpinLog model
 */
export interface SpinLogFieldRefs {
  readonly id: Prisma.FieldRef<"SpinLog", 'Int'>
  readonly employeeId: Prisma.FieldRef<"SpinLog", 'Int'>
  readonly prizeId: Prisma.FieldRef<"SpinLog", 'Int'>
  readonly timestamp: Prisma.FieldRef<"SpinLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SpinLog findUnique
 */
export type SpinLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
  /**
   * Filter, which SpinLog to fetch.
   */
  where: Prisma.SpinLogWhereUniqueInput
}

/**
 * SpinLog findUniqueOrThrow
 */
export type SpinLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
  /**
   * Filter, which SpinLog to fetch.
   */
  where: Prisma.SpinLogWhereUniqueInput
}

/**
 * SpinLog findFirst
 */
export type SpinLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
  /**
   * Filter, which SpinLog to fetch.
   */
  where?: Prisma.SpinLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpinLogs to fetch.
   */
  orderBy?: Prisma.SpinLogOrderByWithRelationInput | Prisma.SpinLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SpinLogs.
   */
  cursor?: Prisma.SpinLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpinLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpinLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SpinLogs.
   */
  distinct?: Prisma.SpinLogScalarFieldEnum | Prisma.SpinLogScalarFieldEnum[]
}

/**
 * SpinLog findFirstOrThrow
 */
export type SpinLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
  /**
   * Filter, which SpinLog to fetch.
   */
  where?: Prisma.SpinLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpinLogs to fetch.
   */
  orderBy?: Prisma.SpinLogOrderByWithRelationInput | Prisma.SpinLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SpinLogs.
   */
  cursor?: Prisma.SpinLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpinLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpinLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SpinLogs.
   */
  distinct?: Prisma.SpinLogScalarFieldEnum | Prisma.SpinLogScalarFieldEnum[]
}

/**
 * SpinLog findMany
 */
export type SpinLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
  /**
   * Filter, which SpinLogs to fetch.
   */
  where?: Prisma.SpinLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SpinLogs to fetch.
   */
  orderBy?: Prisma.SpinLogOrderByWithRelationInput | Prisma.SpinLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SpinLogs.
   */
  cursor?: Prisma.SpinLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SpinLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SpinLogs.
   */
  skip?: number
  distinct?: Prisma.SpinLogScalarFieldEnum | Prisma.SpinLogScalarFieldEnum[]
}

/**
 * SpinLog create
 */
export type SpinLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
  /**
   * The data needed to create a SpinLog.
   */
  data: Prisma.XOR<Prisma.SpinLogCreateInput, Prisma.SpinLogUncheckedCreateInput>
}

/**
 * SpinLog createMany
 */
export type SpinLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SpinLogs.
   */
  data: Prisma.SpinLogCreateManyInput | Prisma.SpinLogCreateManyInput[]
}

/**
 * SpinLog createManyAndReturn
 */
export type SpinLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
  /**
   * The data used to create many SpinLogs.
   */
  data: Prisma.SpinLogCreateManyInput | Prisma.SpinLogCreateManyInput[]
}

/**
 * SpinLog update
 */
export type SpinLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
  /**
   * The data needed to update a SpinLog.
   */
  data: Prisma.XOR<Prisma.SpinLogUpdateInput, Prisma.SpinLogUncheckedUpdateInput>
  /**
   * Choose, which SpinLog to update.
   */
  where: Prisma.SpinLogWhereUniqueInput
}

/**
 * SpinLog updateMany
 */
export type SpinLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SpinLogs.
   */
  data: Prisma.XOR<Prisma.SpinLogUpdateManyMutationInput, Prisma.SpinLogUncheckedUpdateManyInput>
  /**
   * Filter which SpinLogs to update
   */
  where?: Prisma.SpinLogWhereInput
  /**
   * Limit how many SpinLogs to update.
   */
  limit?: number
}

/**
 * SpinLog updateManyAndReturn
 */
export type SpinLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
  /**
   * The data used to update SpinLogs.
   */
  data: Prisma.XOR<Prisma.SpinLogUpdateManyMutationInput, Prisma.SpinLogUncheckedUpdateManyInput>
  /**
   * Filter which SpinLogs to update
   */
  where?: Prisma.SpinLogWhereInput
  /**
   * Limit how many SpinLogs to update.
   */
  limit?: number
}

/**
 * SpinLog upsert
 */
export type SpinLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
  /**
   * The filter to search for the SpinLog to update in case it exists.
   */
  where: Prisma.SpinLogWhereUniqueInput
  /**
   * In case the SpinLog found by the `where` argument doesn't exist, create a new SpinLog with this data.
   */
  create: Prisma.XOR<Prisma.SpinLogCreateInput, Prisma.SpinLogUncheckedCreateInput>
  /**
   * In case the SpinLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SpinLogUpdateInput, Prisma.SpinLogUncheckedUpdateInput>
}

/**
 * SpinLog delete
 */
export type SpinLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
  /**
   * Filter which SpinLog to delete.
   */
  where: Prisma.SpinLogWhereUniqueInput
}

/**
 * SpinLog deleteMany
 */
export type SpinLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SpinLogs to delete
   */
  where?: Prisma.SpinLogWhereInput
  /**
   * Limit how many SpinLogs to delete.
   */
  limit?: number
}

/**
 * SpinLog without action
 */
export type SpinLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpinLog
   */
  select?: Prisma.SpinLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SpinLog
   */
  omit?: Prisma.SpinLogOmit<ExtArgs> | null
}
